version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - task
  webapi:
    container_name: taskapi
    image: taskapi
    build: .
    ports:
      - "3000:3000"
    restart: always
    links:
      - mongo
    networks:
      - task
volumes:
  db_data:
networks:
  task: