version: '3'
services:
   mongo:
     container_name: mongo
     image: mongo
     volumes:
      - db_data:/data/db
     ports:
      - "27017:27017"
   webapi:
     container_name: taskwebapi
     image: taskwebapi
     ports:
       - "3000:3000"
     restart: always
     links:
      - mongo
volumes:
  db_data: